import{S as g,i as c,a as h}from"./assets/vendor-D0cagnvz.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const l of e.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function s(t){if(t.ep)return;t.ep=!0;const e=i(t);fetch(t.href,e)}})();const p=document.querySelector(".gallery"),a=document.createElement("button");a.classList.add("loadButton");a.textContent="Load More";let b=new g(".gallery a",{captionsData:"alt",captionDelay:250});function F(r){let o="";const i=p.children.length;r.forEach(e=>{o+=`
      <li class="image">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" width="360" height="200">
          <div class="imageStats">
          <p><span>Likes</span>${e.likes}</p>
          <p><span>Views</span> ${e.views}</p>
          <p><span>Comments</span> ${e.comments}</p>
          <p><span>Downloads</span> ${e.downloads}</p>
          </div>
          </a>
      </li>
    `}),p.insertAdjacentHTML("beforeend",o),b.refresh(),a.style.display="block",document.body.append(a);const s=document.querySelectorAll(".image"),t=s[i];if(s.length>15){const e=t.getBoundingClientRect();window.scrollBy({top:e.top-20,behavior:"smooth"})}}const y=document.querySelector(".searchPhoto");let u=1,m=15,d="";async function f(){try{let r=y.inputText.value.trim();if(d!=r&&(d=r,p.innerHTML="",a.style.display="none"),!r){c.error({color:"#EF4040",message:"Error, input field is empty",messageColor:"#FAFAFB",maxWidth:"432",iconColor:"#FAFAFB"});return}const o=await h.get(`https://pixabay.com/api/?key=48639504-554e542bc8495b3a6c3499497&q=${d}&image_type=photo&orientation=horizontal&safesearch=true&page=${u}&per_page=15`);if(o.data.totalHits<=m&&(a.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results."})),o.data.hits.length===0){c.error({color:"#EF4040",message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"#FAFAFB",maxWidth:"432",iconColor:"#FAFAFB"});return}u+=1,m+=15,F(o.data.hits)}catch(r){console.log(r)}}const n=document.createElement("span");n.classList.add("loader");y.addEventListener("submit",async r=>{r.preventDefault(),document.body.append(n);try{await f()}catch(o){console.error(o)}finally{document.body.removeChild(n)}});a.addEventListener("click",async r=>{r.preventDefault(),document.body.append(n),a.style.display="none";try{await f()}catch(o){console.error(o)}finally{document.body.removeChild(n),a.style.display="block"}});
//# sourceMappingURL=index.js.map
