import{S as g,i as c,a as d}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const t of o.addedNodes)t.tagName==="LINK"&&t.rel==="modulepreload"&&a(t)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const u=document.querySelector(".gallery"),n=document.createElement("button");n.classList.add("loadButton");n.textContent="Load More";let h=new g(".gallery a",{captionsData:"alt",captionDelay:250});function p(i){let r="";const a=document.querySelectorAll(".image").length;i.forEach(t=>{r+=`
      <li class="image">
        <a class="gallery-link" href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image" width="360" height="200">
          <div class="imageStats">
          <p><span>Likes</span>${t.likes}</p>
          <p><span>Views</span> ${t.views}</p>
          <p><span>Comments</span> ${t.comments}</p>
          <p><span>Downloads</span> ${t.downloads}</p>
          </div>
          </a>
      </li>
    `}),u.innerHTML+=r,h.refresh(),n.style.display="block",document.body.append(n);const e=document.querySelectorAll(".image"),o=e[a];if(e.length>15){const t=o.getBoundingClientRect();window.scrollBy({top:t.top-20,behavior:"smooth"})}}const m=document.querySelector(".searchPhoto"),l=document.createElement("span");l.classList.add("loader");async function y(i){try{let r=m.inputText.value.trim(),s="",a=1,e=15;if(s!=r&&(s=r,a=1,u.innerHTML="",n.style.display="none"),!r){c.error({color:"#EF4040",message:"Error, input field is empty",messageColor:"#FAFAFB",maxWidth:"432",iconColor:"#FAFAFB"});return}document.body.append(l);const o=await d.get(`https://pixabay.com/api/?key=48639504-554e542bc8495b3a6c3499497&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${a}&per_page=15`);if(document.body.removeChild(l),o.data.hits.length===0){c.error({color:"#EF4040",message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"#FAFAFB",maxWidth:"432",iconColor:"#FAFAFB"});return}p(o.data.hits),n.addEventListener("click",async()=>{try{a+=1,e+=15,document.body.append(l);const t=await d.get(`https://pixabay.com/api/?key=48639504-554e542bc8495b3a6c3499497&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${a}&per_page=15`);document.body.removeChild(l),console.log(t),p(t.data.hits),t.data.totalHits<=e&&(n.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results."}))}catch(t){console.log(t)}})}catch(r){console.log(r)}}m.addEventListener("submit",i=>{i.preventDefault(),y()});
//# sourceMappingURL=index.js.map
